name: 'Read a JSON file and load all values as environment variables'
description: 'Read and load all values from json file, set environment variables to be used in workflow.'
author: 'Dick Lundblad'
inputs:
  json_file:
    description: 'The path to the JSON file to be loaded.'
    required: false
    default: 'config.json'
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    INPUT_JSON_FILE: ${{ inputs.json_file }}  # Pass the input as an environment variable

